config/routes.rb
Rails.application.routes.draw do
  resources :apps do
    collection { get "search" }
  end
  root "top#index"
  get "apps/:id/download" => "apps#download"
  get "apps/:id/delete" => "apps#delete"
end

app/models/app.rb
class App < ApplicationRecord
    validates( :name, presence: { message: "アプリの名前を入力してください。" } )
    validates( :appid, presence: { message: "アプリIDを入力してください。" },
    uniqueness: { message: "そのアプリIDはすでに登録されています。" })
    validates( :author, presence: { message: "アプリの作者名を入力してください。" } )
    validates( :data, presence: { message: "アプリの本体(zipファイル)を選択してください。" } )
    class << self
        def search(q)
            rel = order("created_at")
            rel = rel.where("name LIKE ? OR appid LIKE ?OR author LIKE ?", "%#{q}%", "%#{q}%", "%#{q}%")
            rel
        end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    render("error") if( !@app.present? )
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(app_params)
    @app.data = params[:app][:data].read if( @app.data.present? )

    if( @app.appid == "new" )
      render(plain: "使用できないアプリケーションIDです。")
      return
    end

    respond_to do |format|
      if @app.save
        format.html { redirect_to "/apps/"+@app.appid, notice: 'App was successfully created.' }
        format.json { render :show, status: :created, location: @app }
      else
        format.html { render :new }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { render :show, status: :ok, location: @app }
      else
        format.html { render :edit }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to apps_url, notice: 'App was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete
    set_app
  end

  def download
    if( App.find_by_id(params[:id]) )
      @app = App.find_by_id(params[:id]) 
    else
      @app = App.find_by_appid(params[:id]) 
    end
    send_data( @app.data, type: "application/zip", filename: @app.appid+".zip" )
  end

  def search
    @apps = App.search(params[:q])
    render("search")
  end

  def error
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      if( App.find_by_id(params[:id]) )
        @app = App.find_by_id(params[:id]) 
      else
        @app = App.find_by_appid(params[:id]) 
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_params
      params.require(:app).permit(:name, :appid, :author, :desc, :genre, :url, :data)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def kithub_title
    if( @title )
      @title + " - kitHub"
    else
      "kitHub"
    end
  end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/apps/_form.html.erb
<%= form_with(model: app, local: true) do |form| %>
  <% if app.errors.any? %>
    <div id="error_explanation">
      <div>エラー(<%= app.errors.count %>)</div>
      <% app.errors.full_messages.each do |message| %>
        <div>・<%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :app_name %>
  </div>
  <div class="field-desc">アプリケーションの名前です(define.jsonにおけるnameに相当)。日本語を使用することができます。</div>

  <div class="field">
    <%= form.label :appid %>
    <%= form.text_field :appid, id: :app_appid %>
  </div>
  <div class="field-desc">アプリケーションの識別子です(define.jsonにおけるidに相当)。他のアプリケーションと重複することはできません。</div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :app_author %>
  </div>
  <div class="field-desc">アプリケーションの作者名です(define.jsonにおけるauthorに相当)。kitHubでは必須の項目です。</div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc, id: :app_desc %>
  </div>
  <div class="field-desc">アプリケーションの説明文です。ダウンロードしようとしている人に向けてアプリを紹介する文章となります(任意)。</div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre, id: :app_genre %>
  </div>
  <div class="field-desc">アプリケーションのジャンルを指定します(任意)。日本語を使用することができます。</div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :app_url %>
  </div>
  <div class="field-desc">アプリまたは作者のWebサイトを指定できます(任意)。</div>

  <div class="field">
    <%= form.label :data %>
    <%= form.file_field :data, id: :app_data, accept: "application/zip" %>
  </div>
  <div class="field-desc">アプリケーションをzipファイルに圧縮したものを選択してください(必須)。zip以外の形式で圧縮しないでください。</div>

  <div class="actions">
    <%= form.submit("確定する") %>
  </div>
<% end %>

app/views/apps/delete.html.erb
<p id="notice"><%= notice %></p>
<% @title = "Delete" %>

<h1>
<%= @app.name %> / delete
<a id="star">Star</a>
</h1>

<div class="main">
  <article>
    <%= link_to("キャンセル", "/apps/"+@app.appid ) %>
    <div class="app-name">アプリケーションの削除</div>
    <div class="desc">この操作は取り消せません。</div>
    以下のアプリケーションを削除しようとしています。
    <div class="app">
      <a>対象</a>
      <div class="app-desc"><strong><%= @app.name %></strong><br><%= @app.desc %></div>
    </div>
    <%= link_to '削除する', @app, method: :delete, data: { confirm: '本当にアプリケーションを削除しますか？(この操作は取り消せません)' } %>
  </article>
</div>

app/views/apps/edit.html.erb
<h1>
<%= @title = "アプリの編集" %>
<a id="star">Star</a>
</h1>

<div class="main">
  <article>
    <%= link_to("アプリのページへ戻る", "/apps/"+@app.appid) %>
    <%= render "form", app: @app %>
  </article>
</div>

app/views/apps/error.html.erb
<p id="notice"><%= notice %></p>
<% @title = "エラー" %>

<h1>
kitHub / error
<a id="star">Star</a>
</h1>

<div class="main">
  <article>
    <div class="app-name">見つかりません</div>
    <div class="desc">アプリケーションが削除されたか、存在しません。</div>
  </article>
</div>

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
<%= @title = "All Apps" %>
<a id="star" onclick="unstar()">Unstar</a>
</h1>

<% @apps.each do |app| %>
  <div class="app">
    <%= link_to( app.author+" / "+app.appid , "/apps/"+app.appid) %>
    <div class="app-desc"><strong><%= app.name %></strong><br><%= app.desc %></div>
  </div>
<% end %>

app/views/apps/new.html.erb
<h1>
<%= @title = "アプリの追加" %>
<a id="star">Star</a>
</h1>

<div class="main">
  <article>
    <%= render "form", app: @app %>
  </article>
</div>

app/views/apps/search.html.erb
<% @title = params[:q] %>

<h1>
search / <%= params[:q] %>
<a id="star">Star</a>
</h1>
    <article>
        <div class="desc">
            「<%= params[:q] %>」の検索結果です(<%= @apps.count %>件)。
        </div>
    </article>
<% @apps.each do |app| %>
  <div class="app">
    <%= link_to( app.author+" / "+app.appid , "/apps/"+app.appid) %>
    <div class="app-desc"><strong><%= app.name %></strong><br><%= app.desc %></div>
  </div>
<% end %>
<% if( @apps.count == 0 ) %>
  <div class="app">
    アプリケーションが見つかりませんでした<br>
    検索ワードを変えて再度お試しください
  </div>
<% end %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>
<% @title = @app.author+"/"+@app.appid %>

<h1>
<%= link_to( @app.author, "/apps/search?q="+@app.author ) %>
/
<strong><%= link_to( @app.appid ) %></strong>
<a id="star" onclick="star()">Star</a>
</h1>

<div class="main">
  <article>
    <%= link_to("ダウンロード", {controller: "apps", action: "download"}, class: "button") %>
    <div class="app-name"><%= @app.name %></div>
    <div class="desc">
      <% if( @app.desc.present? ) %>
        <%= @app.desc %>
      <% else %>
        説明はありません。
      <% end %>
    </div>
    アプリの作者<br>
    <%= link_to( @app.author, "/apps/search?q="+@app.author ) %><br>
    ジャンル<br>
    <% if( @app.genre.present? ) %>
      <%= @app.genre %>
    <% else %>
      未登録
    <% end %>
    <br>
    作者のWebサイト<br>
    <% if( @app.url.present? ) %>
      <%= link_to( "Webサイトへアクセス", @app.url ) %>
    <% else %>
      未登録
    <% end %><br>
    アプリの操作<br>
    <%= link_to '編集', edit_app_path(@app.appid) %> / 
    <%= link_to '削除', {controller: "apps", action: "delete"} %><br>
  </article>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= kithub_title() %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, maximum-scale=1">
    <meta name="format-detection" content="telephone=no">
  </head>

  <body>
    <header>
    <%= link_to( image_tag("logo.png"), :root ) %>
    <span>beta</span>
    <%= form_tag( :search_apps, method: :get) do %>
      <%= text_field_tag( "q", params[:q], placeholder: "検索" ) %>
    <% end %>
    </header>
    <%= yield %>
    <footer>
      ©2019 kitHub
      <%= link_to("すべてのアプリ", apps_path) %>
      <%= link_to("アプリの追加", new_app_path) %>
      <% if( cookies[:star] ) %>
        <%= link_to("★", cookies[:star]) %>
      <% end %>
    </footer>
  </body>
</html>

app/views/top/index.html.erb
<h1>
kitHub / Home
<a id="star">Star</a>
</h1>
<div class="main">
    <article>
        <div class="desc">
            kitHubのメインページです。
        </div>
        kitHub ベータ版 v0.1.1へようこそ。<br>
        ・<%= link_to("kitHubアプリの一覧", apps_path) %> アプリケーションの一覧です<br>
        ・<%= link_to("kitHubにアプリを投稿する", new_app_path) %> 自身のアプリをkitHubに追加できます<br>
        ・<a href="http://web.kitit.ml/">kitのホームページ(リンク)</a> kit Desktop Systemのホームページです<br>
        ・<a href="https://kitdev.home.blog/">kitブログ(リンク)</a> kitの開発ブログです<br>
        <%= image_tag("banner.png", class: "image") %><br>
        kitHubはベータ版です。以下のような機能は今後のデータベースの移行を伴う大きなアップデートによって実装される予定です。<br>
        ・ユーザーアカウントによるアプリケーションの管理機能<br>
        ・テーマファイルのアップロードとダウンロード<br>
        ・define.jsonからのアプリケーション情報の自動読み込み<br>
        ・バージョン情報の登録機能<br>
        ・kitHubAPIの整備とkitシステムへの自動インストール<br>
        Star機能について<br>
        　アプリケーションのページでStarを押すと登録できます。1件のみ登録でき、すでに登録されているものは上書きされます。<br>
        　登録するとフッターからアクセスできるようになります(turbolinksによってすぐに反映されない場合があります)。動作が不安定なため、今後のアップデートで改善もしくは機能削除予定です。<br>
        既知の不具合<br>
        ・アプリケーションのデータを編集で更新するとデータが損失する
    </article>
</div>